# Project-wide Gradle settings.
kotlin.code.style=official

# Versions
kotlin.version=2.0.0
agp.version=8.5.2
compose.version=1.7.0

# Multiplatform Settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.mpp.enableIntrinsicConstEvaluation=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.mpp.androidSourceSetLayoutVersion=2
